version: '3.9'
services:
  node:
    container_name: ${IW_NODE_IMAGE}
    build:
      context: ./
    command: 'yarn dev'
    ports:
      - ${NODE_HOST_PORT}:${NODE_CONTAINER_PORT}
    volumes:
      - ${PWD}:/app

  mysql:
    container_name: ${DB_CONTAINER_NAME}
    image: mariadb:10.5
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .database.env

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - ${AD_HOST_PORT}:${AD_CONTAINER_PORT}
    env_file:
      - .database.env
volumes:
  database:
